[project]
name = "server-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "customtkinter>=5.2.2",
    "websocket>=0.2.1,<15.0.2",
    "websocket-client>=1.9.0",
    "websockets>=15.0.1",
]
